config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'

  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 600 }
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  mount_uploader :image, ImageUploader

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
      
  end

  def update  
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted"
    redirect_to recipes_path
  end

  def like 
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to root_path
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to root_path
    end
  end

  private 

  def set_recipe
     @recipe = Recipe.find(params[:id])
   end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :image, :remove_image, ingredient_ids:[])
  end

  def require_same_user
    if current_chef !=@recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own recipes!"
      redirect_to recipes_path
    end
  end

  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform action"
      redirect_to root_path
    end
  end

end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<%= form_for(@recipe, html: { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>

  <div class="row">
    <div class="col-md-12">

      <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-md-10 offset-1">
            <%= f.label :name %>
          </div>
          <div class="col-md-10 offset-1">
            <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-10 offset-1">
            <%= f.label :decription %>
          </div>
          <div class="col-md-10 offset-1">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-10 offset-1">
             <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb|%>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
             <% end %> 
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-10 offset-1">
            <%= f.label :image, "Add Image" %>
          </div>
          <div class="col-md-10 offset-1">
            <%= f.file_field :image, accept: 'image/jpeg,iamge/gif,image/png' %>

              <% if @recipe.image? %>
                  <%= image_tag @recipe.image.url if @recipe.image? %>
                <%= f.check_box :remove_image %>
                  Remove Image
              <% end %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-10 offset-1">
            <%= f.submit class: "btn btn-primary btn-lg create" %>
          </div>
        </div>
      <% end %>
        <div class="col-md-4 offset-4 cancel">
          <%=link_to "Cancel request and return to recipes listing", recipes_path, class: "tag" %>
        </div>

    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <%= image_tag(recipe.image.url, size: "100x100", class: "recipe-img")if recipe.image? %>
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 85) %>
      </section>
    </div>
    <div class="col-md-8 well" >
      <%= link_to recipe.name, recipe_path(recipe), class: "link-font" %>
      <p class="descrip"><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
        <% end %>
      <p>
        <span class="quiet">Created <%= time_ago_in_words(recipe.created_at) %> ago by: <%= recipe.chef.chefname.capitalize %>  | <%= pluralize(recipe.comments.count, 'Comment') %></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin) %>
        <div class="recipe-actions">
          <%= link_to "Edit recipe", edit_recipe_path(recipe), class: "btn btn-success btn-sm" %>
          <%= link_to "Delete recipe", recipe_path(recipe), method: :delete,
                                        data: { confirm: "Are you sure?" },
                                        class: "btn btn-danger btn-sm" %>
        </div>
      <% end %>

      <div class="row">
        <div calss="pull-left liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="fas fa-smile-beam"></i>
          <% end %> <%= recipe.thumbs_up_total %>
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="fas fa-frown"></i>
          <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>
    </div>
  </div> 
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Recipes" %>

<%= render 'recipe', obj: @recipes %>


<div class="digg_pagination">
    <%= will_paginate @recipes, :container => true %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="col-md-6 offset-3">
  <div align="center">
    <%= image_tag @recipe.image.url if @recipe.image? %>
  </div>

  <h4 class="description"><storng>Steps: </storng></h4>
  <hr />
  <%= simple_format(@recipe.description) %>
  <hr />
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="text-right chef">
    <p class="center">
        Created by:
    </p>
    <p class="center icon">
      <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <%= @recipe.chef.chefname.capitalize %>
      <div class="text-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-action">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit recipe", edit_recipe_path(@recipe), class: "btn btn-success btn-sm" %>
      <%= link_to "Delete recipe", recipe_path(@recipe), method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      class: "btn btn-danger btn-sm" %>
    <% end %>
    <%= link_to "Return to recipes", recipes_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-12">
      <h3>Comments: </h3>
      <hr />
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %> 
        <div class="form-group">
          <div class="col-md-10 offset-1">
            <%= f.label :comment %>
          </div>
          <div class="col-md-10 offset-1">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter comment here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-10 offset-1">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg create" %>
          </div>
        </div>
      <% end %>
       <hr />
    </div>
  </div>
    <!--<div class="row liking">
      <div class="row col-md-6 offset-2">
        <%#= link_to like_recipe_path(@recipe, like:true), method: :post do %>
          <i class="fas fa-smile-beam"></i>
        <%# end %> <%= @recipe.thumbs_up_total %>
        <%#= link_to like_recipe_path(@recipe, like:false), method: :post do %>
          <i class="fas fa-frown"></i>
        <%# end %> <%= @recipe.thumbs_down_total %>
      </div>
    </div>-->
<% end %>

<% if @recipe.comments != 0 %>
  <div class="row">
    <div class="col-md-10 offset-2">
      <h3>Prior Comments:</h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>