config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'

  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
end

app/views/layouts/_alerts.html.erb
<div class="row">
  <div class="col-md-10 offset-1">

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
         <%= msg %>
      </div> 
    <% end %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="card-footer">

<footer>Copyright &copy; 2018 Rob Brown</footer>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  
  <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="nav-item active">
        <%= link_to "Chefs" , chefs_path, class: "link c" %>
        <%= link_to "All Recipes", recipes_path, class: "link r" %>
      </div>
      <% if logged_in? %> 
        <%= link_to "ChefChat", chat_path, class: "link chef" %> 
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipes
          </a>
          <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
            <%= link_to "Create a new recipe", new_recipe_path, class: "new-recipe" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
      <% end %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ingredients
          </a>
          <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
            <%= link_to "All Ingredients", ingredients_path, class: "ingredient" %>
              <% Ingredient.all.each do |ingredient| %>
                <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient), class: "each-ing" %></li>
              <% end %>
            <% if logged_in? && current_chef.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to "New Ingredients", new_ingredient_path, class: "new-ing" %>
            <% end %>
          </div>
        </div>
    </ul>
    <div class="navbar-nav search mr-auto">
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>

    <% if logged_in? %>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %>
        </a>
        <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
          <li><%= link_to "View your profile", chef_path(current_chef), class: "pf-view" %></li>
          <li><%= link_to "Edit your profile", edit_chef_path(current_chef), class: "pf-edit" %></li>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", logout_path, method: :delete, class: "pf-logout" %>
        </div>
      </div>
      <% else %>
      <%= link_to "log in", login_path, class: "nav-login" %>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  </body>
</html>